### PR TITLE
Update dev_master workspace

### PR DESCRIPTION
**Pull request by Jasonface900**

### CODE REVIEW

**Comment by JWCS** [comment]
Hey, you have quite a bit of fancy code you're working with. Something you should definitely finish before continuing is to have at least 1 finished version- a barebones version. A piece of code we can drop on the rio as is, fully tested. Having just one or two branches with no releases or finished pieces is not progress. 
Oh, and take a look at "Switch" statements, that might simplify your code.

**Comment by Jasonface900** [comment]
The master code is the barebones code that controls the arm, the claw, the wheels, but it has the added functionality of a speed button. We're working on how to get swich case to receive controller input using the getRawButton function.

**Comment by JWCS** [comment]
I meant the excessive use of buttons and "settings." Barebones would be more so like having 1 feature being completely controlled by 1 joystick axis (which has scaled positive negative values) or 2 buttons (a static positive value and a static negative value). Also, when the code for different features gets grouped together, it induces complexity and error possibility. 
I'm not saying that the final code won't be complex, multi-feature integrating, and with heavy UI, but there is a definite version that minimizes lines, feature interaction, and UI, and that is barebones code. If something happened to the libraries or at competition & the complex code doesn't work*, you pull up the barebones (designed specifically to 100% minimize error & problems) and build up from there. 
*Which has happened every year so far (fingers crossed).

**Comment by Jasonface900** [comment]
So, do you recommend we just leave only movement controls, like move arm + claw + wheels, and remove the variable speed controls?

**Comment by JWCS** [comment]
For the barebones version, it should just be initialization, variables, supporting structural code (b/c it's using the WPI library and being executed by a program calling for different structures etc.), and the motion code. The motion code can have variable values if it's a simple implementation. As mentioned above, the simple way is to tie a joystick axis (variable) or pair of buttons (static) to each feature. For example, the arm and claw code were 1 line each, and the mec drive code was effectively 3 lines: a state set by a button and a call to to the mec drive function for each state. 
Also, look at "switch" statements for multiple different states.

**Pull request merged**
